### ISSUE TITLE
Provide unauthenticated endpoint for Prometheus

### ISSUE THREAD

**Issue by hectorhuertas** [Graylog2/graylog-plugin-metrics-reporter#29]
Hi,

Would it be possible to provide an unauthenticated endpoint for the Prometheus exporter?

We are running graylog inside kubernetes, where the authentication doesn't play nice with Prometheus' kubernetes service discovery and would like to avoid having a custom configuration just for graylog.

Thanks

**Comment by runningman84** [comment]
@jalogisch is there any chance to get this feature with 3.x?

**Comment by george-angel** [comment]
We found an acceptable workaround by running a side-car pushgateway container in the same pod (we run Graylog on kubernetes)

```
      - name: pushgateway
        image: prom/pushgateway:v0.5.2
        livenessProbe:
          httpGet:
            path: /#/status
            port: 9091
        readinessProbe:
          httpGet:
            path: /#/status
            port: 9091
        resources:
          requests:
            memory: 10Mi
          limits:
            memory: 100Mi
        ports:
          - name: metrics
            containerPort: 9091
```
